# Generated by Django 5.2.17 on 2026-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_twofactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
