# Generated by Django 5.2.17 on 2026-09-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_shift_end_profile_shift_start"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="denied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrator who approved or denied this account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("nurse", "Nurse"),
                    ("receptionist", "Receptionist"),
                    ("physician", "Physician"),
                    ("administrator", "Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
