# Generated by Django 5.2.17 on 2026-09-28 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="triage",
            name="height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(250),
                ],
                verbose_name="Height (cm)",
            ),
        ),
    ]
