# Generated by Django 5.2.17 on 2026-09-28 07:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0002_triage_height_cm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="triage",
            name="identity_verified",
            field=models.BooleanField(
                default=False,
                help_text="Name and date of birth were checked with the patient.",
            ),
        ),
        migrations.AddField(
            model_name="triage",
            name="override_reason",
            field=models.CharField(
                blank=True,
                help_text="Why a lower priority than suggested was chosen.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="triage",
            name="pain_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Pain score (0-10)",
            ),
        ),
        migrations.AddField(
            model_name="triage",
            name="respiratory_rate",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(80),
                ],
                verbose_name="Respiratory rate (breaths/min)",
            ),
        ),
        migrations.AddField(
            model_name="triage",
            name="suggested_priority",
            field=models.CharField(
                blank=True,
                help_text="What the vitals suggested when this was saved.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TriageAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=60)),
                ("old_value", models.CharField(blank=True, max_length=60)),
                ("new_value", models.CharField(blank=True, max_length=60)),
                ("reason", models.CharField(max_length=255)),
                ("amended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="triage.triage",
                    ),
                ),
            ],
            options={
                "ordering": ["amended_at"],
            },
        ),
    ]
