# Generated by Django 5.2.17 on 2026-09-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive patients stay in the archive; nothing is deleted.",
                verbose_name="active",
            ),
        ),
    ]
