# Generated by Django 5.2.17 on 2026-09-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Widowed", "Widowed"),
                    ("Divorced", "Divorced"),
                    ("Separated", "Separated"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_relationship",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male")],
                max_length=10,
                verbose_name="biological sex",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A-Positive"),
                    ("A-", "A-Negative"),
                    ("B+", "B-Positive"),
                    ("B-", "B-Negative"),
                    ("AB+", "AB-Positive"),
                    ("AB-", "AB-Negative"),
                    ("O+", "O-Positive"),
                    ("O-", "O-Negative"),
                ],
                max_length=3,
            ),
        ),
    ]
