# Generated by Django 5.2.17 on 2026-09-28 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_patientchange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The student portal account that may see this record. Linked by clinic staff after checking ID.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
