# Generated by Django 5.2.17 on 2026-09-28 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "history",
            "0004_visit_closed_by_visit_closed_reason_visit_triage_by_and_more",
        ),
        ("patients", "0005_patient_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="patient_summary",
            field=models.TextField(
                blank=True,
                help_text="Plain-language summary the patient sees in their portal. Optional.",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lab", "Lab report"),
                            ("imaging", "Imaging report"),
                            ("referral", "Referral letter"),
                            ("certificate", "Medical certificate"),
                            ("outside", "Outside medical record"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("filename", models.CharField(max_length=150)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("content", models.BinaryField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("clinic", "Clinic"),
                            ("patient", "Sent by the patient"),
                        ],
                        default="clinic",
                        max_length=10,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("pending", "Awaiting review"),
                            ("rejected", "Not accepted"),
                        ],
                        default="accepted",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=255)),
                (
                    "visible_to_patient",
                    models.BooleanField(
                        default=True,
                        help_text="Show this file in the patient's portal.",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_reason", models.CharField(blank=True, max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="patients.patient",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="history.visit",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
