# Generated by Django 5.2.17 on 2026-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditentry_entry_hash_auditentry_prev_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentry",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="auditentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("MODIFIED", "Modified"),
                    ("AUTHORIZED", "Authorized"),
                    ("SYSTEM", "System"),
                    ("SIGN_IN", "Sign in"),
                    ("SIGN_IN_FAILED", "Failed sign-in"),
                ],
                max_length=16,
            ),
        ),
    ]
